name: Build Server Image
description: Builds and publishes the docker image for the Spacedrive server
inputs:
  gh_token:
    description: 'A Github PAT'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.gh_token }}

    - name: Build Server
      shell: bash
      run: |
        cargo build --release -p server
        cp ./target/release/server ./apps/server/server

    - name: Determine image name & tag
      shell: bash
      run: |
        if [ "$GITHUB_EVENT_NAME" == "release" ]; then
          export IMAGE_TAG=${GITHUB_REF##*/}
        else
          export IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA")
        fi
        export GITHUB_REPOSITORY_LOWER=$(echo $GITHUB_REPOSITORY | awk '{print tolower($0)}')
        export IMAGE_NAME="ghcr.io/$GITHUB_REPOSITORY_LOWER/server"
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "Building $IMAGE_NAME:$IMAGE_TAG"

    - name: Build Docker image
      shell: bash
      run: |
        docker build ./apps/server --tag $IMAGE_NAME:$IMAGE_TAG

    - name: Push Docker image
      shell: bash
      if: github.event_name != 'pull_request'
      run: |
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Tag & push image as latest staging image
      if: github.event_name != 'release'
      shell: bash
      run: |
        docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:staging
        docker push $IMAGE_NAME:staging

    - name: Tag & push image as latest production image
      if: github.event_name == 'release'
      shell: bash
      run: |
        docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:production
        docker push $IMAGE_NAME:production
